
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Jun  3 2025 21:35:02 CST (Jun  4 2025 03:35:02 UTC)

// Verification Directory fv/counter 

module counter(clk_i, rst_n_i, q_o);
  input clk_i, rst_n_i;
  output [2:0] q_o;
  wire clk_i, rst_n_i;
  wire [2:0] q_o;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  DFFX0 \q_o_reg[2] (.CN (n_13), .D (n_14), .Q (q_o[2]), .QN (n_0));
  NORX0 g58__2398(.A (n_11), .B (n_10), .Y (n_14));
  DFFX0 \q_o_reg[1] (.CN (n_13), .D (n_12), .Q (q_o[1]), .QN (n_1));
  NORX0 g59__5107(.A (n_11), .B (n_8), .Y (n_12));
  NORX0 g60__6260(.A (n_7), .B (n_9), .Y (n_10));
  DFFX0 \q_o_reg[0] (.CN (n_13), .D (n_3), .Q (q_o[0]), .QN (n_2));
  NORX0 g63__4319(.A (n_0), .B (n_5), .Y (n_9));
  NANDX0 g64__8428(.A (n_6), .B (n_4), .Y (n_8));
  NORX0 g61__5526(.A (q_o[2]), .B (n_6), .Y (n_7));
  INVX0 g66(.A (n_6), .Y (n_5));
  NANDX0 g67__6783(.A (n_2), .B (n_1), .Y (n_4));
  NORX0 g65__3680(.A (n_11), .B (q_o[0]), .Y (n_3));
  NANDX0 g68__1617(.A (q_o[1]), .B (q_o[0]), .Y (n_6));
  INVX0 g71(.A (rst_n_i), .Y (n_11));
  INVX0 g69(.A (clk_i), .Y (n_13));
endmodule

